version: "3.9"
services:
  mysql:
    platform: linux/x86_64
    container_name: thaibev
    image: mysql:5.7.37
    command: --default-authentication-plugin=mysql_native_password
    restart: no
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: usr
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - 3306:3306

